FROM node:20

RUN apt-get update && apt-get install apt-file -y && apt-file update
RUN apt-get install vim -y

WORKDIR /usr/src/app/front-end

COPY --chown=node:node ./ ./ 

RUN npm install
RUN npm run build

CMD ["npm", "run", "start"]